spring.application.name=c4h142
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

security.jwt.secret=Zmlyc3RzZWNyZXRLZXlmb3JjNHIxMTR0aF9qd3RfcnJfMjAyNg==
security.jwt.expiration-ms=86400000
